### PR TITLE
Audio Files Placed

### PR DESCRIPTION
**Pull request by molongjoe**
I created a helper function (PlaySound) in the GameManager and PlayerManager scripts to facilitate the new voice over clips I did. The clips are now in the MySounds folder. Clips are played at the correct times. Randomization was left out for all except the death sounds. If this is acceptable, I'll randomize the rest as well (by randomize, I mean have different, but similar clips set to play after the same event, so as to keep the repetition down).

PlaySound chooses the audio clip with a string switch statement. It would be a lot easier to pass audioclips to the method as parameters, but RPC calls deal with streaming objects like audio clips in very specific ways using serialization. This will suffice for now.

### CODE REVIEW

**Comment by ndru-pi-squared** [comment]
The sounds are fun! Seems like some of them overlap, but that's fine for now and the way the audio source is set up it doesn't seem to get too noisey when they overlap

**Comment by kmbosworth321** [comment]
Works for me, let's merge!

**Comment by ndru-pi-squared** [comment]
Let's get mobile in there first, and then weapons, and then this imo since this isn't a demo 3 feature

**Comment by ndru-pi-squared** [comment]
Closed this because I added it to the wD3 branch in the scramble before demo 3

**Pull request closed without merging**
