### PR TITLE
Simple room has medkit, frag grenades on map. There are a few extra spawn points and the instantiation of weapons on the map is iterative

### PR DESCRIPTION
**Pull request by ndru-pi-squared**
They are only in Simple Room for now. Simple Room 2 will not be hard, but we need to pull Jeremy's Space_Arena changes and then I will add the bonus spawn points and items in that level. 

Medkits and Grenades are handled separately from Guns, and they do not have any UI elements associated which tell you that you possess a grenade or medkit. That will come in my next branch/pull request. 

Press H to use a medkit after taking damage. Press F to "throw" a grenade after picking it up. Press P to give yourself a grenade (for testing purposes only).

IIRC I've also included the indicator for master client role: "-MC" is appended to the player name in the top panel.

### CODE REVIEW

**Comment by kmbosworth321** [comment]
Not sure 100% what's still WIP and what's a bug, but I was having a difficult time getting the pickups. E.g. I would walk over a grenade, it wouldn't disappear off the map or indicate that it had been retrieved, and then when I press 'f' sometimes it would throw a grenade and other times it would not.

**Review by molongjoe — APPROVED** [review]
Works well enough for me. There are some sync issues I notice when playing with two players in a room, the medkit and grenade didn't spawn for the second player to enter sometimes. I know that they only spawn on one side, but it didn't spawn there one time when I started it. However, that's hardly an issue for the demo scope in my opinion, so this gets my +1

**Comment by ndru-pi-squared** [comment]
Ben they should be spawning on both sides, 1 grenade and 1 medkit on each

**Comment by ndru-pi-squared** [comment]
I actually may close this because I branched off of it earlier without really thinking and made my UI changes there. I figure at this point that pushing it all together might be easier than pushing just this by itself, but I will leave this open for now.

**Pull request closed without merging**
